app:
  provider:
    postgres:
      client:
        databaseurl: localhost:5432
        username: pismo
        password: pismo
        databasename: pismo
  server:
    loglevel: info
    port: 8081
