definitions:
  request.CreateAccount:
    properties:
      document_number:
        type: string
    required:
    - document_number
    type: object
  response.Account:
    properties:
      account_id:
        type: integer
      document_number:
        type: string
    type: object
info:
  contact: {}
paths:
  /accounts:
    post:
      consumes:
      - application/json
      description: Create an account by given document number
      parameters:
      - description: document number for account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/request.CreateAccount'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Account'
        "400":
          description: Bad Request
          schema: {}
        "406":
          description: Not Acceptable
          schema: {}
      summary: Create an account
      tags:
      - Account
  /health:
    get:
      consumes:
      - application/json
      description: Check health of api
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "406":
          description: Not Acceptable
          schema: {}
      summary: Check health of api
swagger: "2.0"
